# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\ncalculator\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x03\"\'\n\x0fMultiplyRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\"\"\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\"%\n\rDivideRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\" \n\x0e\x44ivideResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\"\'\n\x0fSubtractRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\"\"\n\x10SubtractResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\"\x17\n\nExpRequest\x12\t\n\x01\x61\x18\x01 \x01(\x02\"\x1d\n\x0b\x45xpResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\"$\n\x0cPowerRequest\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\"\x1f\n\rPowerResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\"\x17\n\nSinRequest\x12\t\n\x01\x61\x18\x01 \x01(\x02\"\x1d\n\x0bSinResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\"\x17\n\nCosRequest\x12\t\n\x01\x61\x18\x01 \x01(\x02\"\x1d\n\x0b\x43osResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\x98\x02\n\x0f\x42\x61sicCalculator\x12\x36\n\x03\x41\x64\x64\x12\x16.calculator.AddRequest\x1a\x17.calculator.AddResponse\x12\x45\n\x08Subtract\x12\x1b.calculator.SubtractRequest\x1a\x1c.calculator.SubtractResponse\x12?\n\x06\x44ivide\x12\x19.calculator.DivideRequest\x1a\x1a.calculator.DivideResponse\x12\x45\n\x08Multiply\x12\x1b.calculator.MultiplyRequest\x1a\x1c.calculator.MultiplyResponse2\xfa\x01\n\x12\x41\x64vancesCalculator\x12\x36\n\x03\x45xp\x12\x16.calculator.ExpRequest\x1a\x17.calculator.ExpResponse\x12<\n\x05Power\x12\x18.calculator.PowerRequest\x1a\x19.calculator.PowerResponse\x12\x36\n\x03Sin\x12\x16.calculator.SinRequest\x1a\x17.calculator.SinResponse\x12\x36\n\x03\x43os\x12\x16.calculator.CosRequest\x1a\x17.calculator.CosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=29
  _globals['_ADDREQUEST']._serialized_end=63
  _globals['_ADDRESPONSE']._serialized_start=65
  _globals['_ADDRESPONSE']._serialized_end=94
  _globals['_MULTIPLYREQUEST']._serialized_start=96
  _globals['_MULTIPLYREQUEST']._serialized_end=135
  _globals['_MULTIPLYRESPONSE']._serialized_start=137
  _globals['_MULTIPLYRESPONSE']._serialized_end=171
  _globals['_DIVIDEREQUEST']._serialized_start=173
  _globals['_DIVIDEREQUEST']._serialized_end=210
  _globals['_DIVIDERESPONSE']._serialized_start=212
  _globals['_DIVIDERESPONSE']._serialized_end=244
  _globals['_SUBTRACTREQUEST']._serialized_start=246
  _globals['_SUBTRACTREQUEST']._serialized_end=285
  _globals['_SUBTRACTRESPONSE']._serialized_start=287
  _globals['_SUBTRACTRESPONSE']._serialized_end=321
  _globals['_EXPREQUEST']._serialized_start=323
  _globals['_EXPREQUEST']._serialized_end=346
  _globals['_EXPRESPONSE']._serialized_start=348
  _globals['_EXPRESPONSE']._serialized_end=377
  _globals['_POWERREQUEST']._serialized_start=379
  _globals['_POWERREQUEST']._serialized_end=415
  _globals['_POWERRESPONSE']._serialized_start=417
  _globals['_POWERRESPONSE']._serialized_end=448
  _globals['_SINREQUEST']._serialized_start=450
  _globals['_SINREQUEST']._serialized_end=473
  _globals['_SINRESPONSE']._serialized_start=475
  _globals['_SINRESPONSE']._serialized_end=504
  _globals['_COSREQUEST']._serialized_start=506
  _globals['_COSREQUEST']._serialized_end=529
  _globals['_COSRESPONSE']._serialized_start=531
  _globals['_COSRESPONSE']._serialized_end=560
  _globals['_BASICCALCULATOR']._serialized_start=563
  _globals['_BASICCALCULATOR']._serialized_end=843
  _globals['_ADVANCESCALCULATOR']._serialized_start=846
  _globals['_ADVANCESCALCULATOR']._serialized_end=1096
# @@protoc_insertion_point(module_scope)
