# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from .import (service_pb2 as service__pb2)

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class BasicCalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/calculator.BasicCalculator/Add',
                request_serializer=service__pb2.AddRequest.SerializeToString,
                response_deserializer=service__pb2.AddResponse.FromString,
                _registered_method=True)
        self.Subtract = channel.unary_unary(
                '/calculator.BasicCalculator/Subtract',
                request_serializer=service__pb2.SubtractRequest.SerializeToString,
                response_deserializer=service__pb2.SubtractResponse.FromString,
                _registered_method=True)
        self.Divide = channel.unary_unary(
                '/calculator.BasicCalculator/Divide',
                request_serializer=service__pb2.DivideRequest.SerializeToString,
                response_deserializer=service__pb2.DivideResponse.FromString,
                _registered_method=True)
        self.Multiply = channel.unary_unary(
                '/calculator.BasicCalculator/Multiply',
                request_serializer=service__pb2.MultiplyRequest.SerializeToString,
                response_deserializer=service__pb2.MultiplyResponse.FromString,
                _registered_method=True)


class BasicCalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Divide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasicCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=service__pb2.AddRequest.FromString,
                    response_serializer=service__pb2.AddResponse.SerializeToString,
            ),
            'Subtract': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtract,
                    request_deserializer=service__pb2.SubtractRequest.FromString,
                    response_serializer=service__pb2.SubtractResponse.SerializeToString,
            ),
            'Divide': grpc.unary_unary_rpc_method_handler(
                    servicer.Divide,
                    request_deserializer=service__pb2.DivideRequest.FromString,
                    response_serializer=service__pb2.DivideResponse.SerializeToString,
            ),
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=service__pb2.MultiplyRequest.FromString,
                    response_serializer=service__pb2.MultiplyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.BasicCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculator.BasicCalculator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BasicCalculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.BasicCalculator/Add',
            service__pb2.AddRequest.SerializeToString,
            service__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.BasicCalculator/Subtract',
            service__pb2.SubtractRequest.SerializeToString,
            service__pb2.SubtractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.BasicCalculator/Divide',
            service__pb2.DivideRequest.SerializeToString,
            service__pb2.DivideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.BasicCalculator/Multiply',
            service__pb2.MultiplyRequest.SerializeToString,
            service__pb2.MultiplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AdvancesCalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exp = channel.unary_unary(
                '/calculator.AdvancesCalculator/Exp',
                request_serializer=service__pb2.ExpRequest.SerializeToString,
                response_deserializer=service__pb2.ExpResponse.FromString,
                _registered_method=True)
        self.Power = channel.unary_unary(
                '/calculator.AdvancesCalculator/Power',
                request_serializer=service__pb2.PowerRequest.SerializeToString,
                response_deserializer=service__pb2.PowerResponse.FromString,
                _registered_method=True)
        self.Sin = channel.unary_unary(
                '/calculator.AdvancesCalculator/Sin',
                request_serializer=service__pb2.SinRequest.SerializeToString,
                response_deserializer=service__pb2.SinResponse.FromString,
                _registered_method=True)
        self.Cos = channel.unary_unary(
                '/calculator.AdvancesCalculator/Cos',
                request_serializer=service__pb2.CosRequest.SerializeToString,
                response_deserializer=service__pb2.CosResponse.FromString,
                _registered_method=True)


class AdvancesCalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Power(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdvancesCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exp': grpc.unary_unary_rpc_method_handler(
                    servicer.Exp,
                    request_deserializer=service__pb2.ExpRequest.FromString,
                    response_serializer=service__pb2.ExpResponse.SerializeToString,
            ),
            'Power': grpc.unary_unary_rpc_method_handler(
                    servicer.Power,
                    request_deserializer=service__pb2.PowerRequest.FromString,
                    response_serializer=service__pb2.PowerResponse.SerializeToString,
            ),
            'Sin': grpc.unary_unary_rpc_method_handler(
                    servicer.Sin,
                    request_deserializer=service__pb2.SinRequest.FromString,
                    response_serializer=service__pb2.SinResponse.SerializeToString,
            ),
            'Cos': grpc.unary_unary_rpc_method_handler(
                    servicer.Cos,
                    request_deserializer=service__pb2.CosRequest.FromString,
                    response_serializer=service__pb2.CosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.AdvancesCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculator.AdvancesCalculator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdvancesCalculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.AdvancesCalculator/Exp',
            service__pb2.ExpRequest.SerializeToString,
            service__pb2.ExpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Power(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.AdvancesCalculator/Power',
            service__pb2.PowerRequest.SerializeToString,
            service__pb2.PowerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.AdvancesCalculator/Sin',
            service__pb2.SinRequest.SerializeToString,
            service__pb2.SinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.AdvancesCalculator/Cos',
            service__pb2.CosRequest.SerializeToString,
            service__pb2.CosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
